
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Download, ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';
import { Book } from '@/components/BookGrid';

const Summary = () => {
  const [currentChapter, setCurrentChapter] = useState(0);
  const [book, setBook] = useState<Book | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const storedBook = localStorage.getItem('selectedBook');
    if (storedBook) {
      setBook(JSON.parse(storedBook));
    } else {
      navigate('/');
    }
  }, [navigate]);

  if (!book) return null;

  return (
    <div className="min-h-screen bg-background p-6 animate-in">
      <div className="max-w-4xl mx-auto space-y-8">
        <motion.header
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-4"
        >
          <Button
            variant="ghost"
            className="mb-4"
            onClick={() => navigate('/')}
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Books
          </Button>
          <h1 className="text-4xl font-bold text-primary-contrast">
            {book.title}
          </h1>
          <p className="text-lg text-gray-400">
            AI-Generated Summary
          </p>
        </motion.header>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="glass-panel p-6">
            <div className="flex justify-between items-center mb-6">
              <div className="space-y-1">
                <h2 className="text-xl font-semibold text-primary-contrast">
                  {book.chapters[currentChapter]}
                </h2>
                <p className="text-sm text-gray-400">
                  Summary generated by AI
                </p>
              </div>
              <Button className="button-gradient">
                <Download className="mr-2 h-4 w-4" />
                Download PDF
              </Button>
            </div>

            <div className="grid grid-cols-12 gap-6">
              <motion.div
                className="col-span-3"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
              >
                <nav className="space-y-2">
                  {book.chapters.map((chapter, index) => (
                    <motion.button
                      key={index}
                      onClick={() => setCurrentChapter(index)}
                      className={`w-full text-left px-4 py-2 rounded-lg transition-colors ${
                        currentChapter === index
                          ? 'bg-primary text-white'
                          : 'hover:bg-primary/20 text-gray-400'
                      }`}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      {chapter}
                    </motion.button>
                  ))}
                </nav>
              </motion.div>

              <motion.div
                className="col-span-9"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.2 }}
              >
                <div className="bg-background-light rounded-lg p-6 border border-white/10">
                  <p className="text-gray-300 leading-relaxed">
                    This is a placeholder for the AI-generated summary. The actual summary
                    will be generated based on the uploaded PDF content and displayed here.
                    Each chapter's summary will focus on key points while maintaining
                    clarity and conciseness.
                  </p>
                </div>
              </motion.div>
            </div>
          </Card>
        </motion.div>
      </div>
    </div>
  );
};

export default Summary;
