
import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Download } from 'lucide-react';

const Summary = () => {
  const [currentChapter, setCurrentChapter] = useState(0);
  const chapters = ['Chapter 1', 'Chapter 2', 'Chapter 3']; // Demo data

  return (
    <div className="min-h-screen bg-background p-6 animate-in">
      <div className="max-w-4xl mx-auto space-y-8">
        <header className="text-center space-y-4">
          <h1 className="text-4xl font-bold text-primary-contrast">
            Your AI-Generated Summary
          </h1>
          <p className="text-lg text-gray-400">
            Clear, concise, and impactful
          </p>
        </header>

        <Card className="glass-panel p-6">
          <div className="flex justify-between items-center mb-6">
            <div className="space-y-1">
              <h2 className="text-xl font-semibold text-primary-contrast">
                {chapters[currentChapter]}
              </h2>
              <p className="text-sm text-gray-400">
                Summary generated by AI
              </p>
            </div>
            <Button className="button-gradient">
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>
          </div>

          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-3">
              <nav className="space-y-2">
                {chapters.map((chapter, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentChapter(index)}
                    className={`w-full text-left px-4 py-2 rounded-lg transition-colors ${
                      currentChapter === index
                        ? 'bg-primary text-white'
                        : 'hover:bg-primary/20 text-gray-400'
                    }`}
                  >
                    {chapter}
                  </button>
                ))}
              </nav>
            </div>

            <div className="col-span-9">
              <div className="bg-background-light rounded-lg p-6 border border-white/10">
                <p className="text-gray-300 leading-relaxed">
                  This is a placeholder for the AI-generated summary. The actual summary
                  will be generated based on the uploaded PDF content and displayed here.
                  Each chapter's summary will focus on key points while maintaining
                  clarity and conciseness.
                </p>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
};

export default Summary;
